server:
  port: 8079
spring:
  datasource:
    hikari:
      schema: salon
      maximum-pool-size: 2
      minimum-idle: 5
  application:
    name: web
  security:
    user:
      name: user
      password: pass
  config:
    import:
      configserver:http://localhost:8888
  cloud:
    openfeign:
      client:
        config:
          clients:
            url: http://localhost:8081
          staff:
            url: http://localhost:8084
          services:
            url: http://localhost:8082
          storage:
            url: http://localhost:8083
          visits:
            url: http://localhost:8085

feign:
  client:
    config:
      clients:
        basic-auth:
          username: user
          password: pass

#server:
#  error:
#    whitelabel:
#      enabled : false
logging:
  level:
    ru.jngvarr: DEBUG
