server:
  port: 8083
spring:
  security:
    user:
      name: user
      password: pass

  application:
    name: storage

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/clients
    username: postgres
    password: password
  sql:
    init:
      mode: always

logging:
  level:
    ru.jngvarr: DEBUG
#    org.springframework.security: TRACE


