version: '3.8'
services:
  eureka:
    build:
      context: eureka
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - app-network

  config-server:
    build:
      context: config-server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - app-network
#    extra_hosts:
#      - "host.docker.internal:host-gateway"

networks:
  app-network:

#  api-gateway:
#    build:
#      context: api-gateway
#    container_name: api-gateway
#    ports:
#      - "8765:8765"
#    networks:
#      - app-network
#
#  angular-client:
#    build:
#      context: angularclient
#    container_name: angular-client
#    ports:
#      - "80:80"
#    networks:
#      - app-network
#
#  auth-service:
#    build:
#      context: auth-service
#    container_name: auth-service
#    ports:
#      - "8089:8089"
#    networks:
#      - app-network
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://147.45.102.248:5432/salondb
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: passw
#    depends_on:
#      - eureka
#      - config-server
#
#  appt-management:
#    build:
#      context: appt-management
#    container_name: appt-management
#    ports:
#      - "8085:8085"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://147.45.102.248:5432/salondb
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: passw
#    networks:
#      - app-network
#    depends_on:
#      - eureka
#      - config-server
#
#  client-management:
#    build:
#      context: client-management
#    container_name: client-management
#    ports:
#      - "8081:8081"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://147.45.102.248:5432/salondb
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: passw
#    networks:
#      - app-network
#    depends_on:
#      - eureka
#      - config-server
#
#  service-management:
#    build:
#      context: service-management
#    container_name: service-management
#    ports:
#      - "8082:8082"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://147.45.102.248:5432/salondb
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: passw
#    networks:
#      - app-network
#    depends_on:
#      - eureka
#      - config-server
#
#  staff-management:
#    build:
#      context: staff-management
#    container_name: staff-management
#    ports:
#      - "8084:8084"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://147.45.102.248:5432/salondb
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: passw
#    networks:
#      - app-network
#    depends_on:
#      - eureka
#      - config-server
#
#  storage-management:
#    build:
#      context: storage-management
#    container_name: storage-management
#    ports:
#      - "8083:8083"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://147.45.102.248:5432/salondb
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: passw
#    networks:
#      - app-network
#    depends_on:
#      - eureka
#      - config-server
#
#networks:
#  app-network:
