server:
  port: 8765

spring:
  application:
    name: api-gateway
  profiles:
    active: eclient
  config:
    import: configserver:http://localhost:8888
#    main:
#      web-application-type:
#        reactive
  cloud:
    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods:
#              - GET
#              - OPTIONS
#              - PUT
#              - POST
#              - DELETE
#              - PATCH
#        add-to-simple-url-handler-mapping: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: clients
          uri: http://localhost:8081/
          predicates:
            - Path=/clients/**
        - id: security
          uri: http://localhost:8089/
          predicates:
            - Path=/users/**
        - id: services
          uri: http://localhost:8082/
          predicates:
            - Path=/services/**
        - id: storage
          uri: http://localhost:8083/
          predicates:
            - Path=/storage/**
        - id: staff
          uri: http://localhost:8084/
          predicates:
            - Path=/staff/**
        - id: appointments
          uri: http://localhost:8085/
          predicates:
            - Path=/visits/**
        - id: eserver
          uri: http://localhost:8761/
          predicates:
            - Path=/eureka/**
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
#  main:
#    web-application-type: reactive