server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:


        git:
          uri: https://github.com/jngvarr/SpringConfig.git
          default-label: main
          basedir: c:\Users\jngva\gb\springConfig\

