server:
  port: 8082
spring:
  security:
    user:
      name: user
      password: pass

  application:
    name: services

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://147.45.102.248:5432/salondb
    username: user
    password: passw
    hikari:
      schema: salon
      maximum-pool-size : 2
  sql:
  init:
      mode: always

logging:
  level:
    ru.jngvarr: DEBUG
#    org.springframework.security: TRACE


