server:
  port: 8761
spring:
  application:
    name: eserver
  config:
    import: config-server:http://host.docker.internal:8888
#    import: config-server:http://localhost:8888
  profiles:
    active: default

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka

