server:
  port: 8079
spring:
  application:
    name: web
  security:
    user:
      name: user
      password: pass

  cloud:
    openfeign:
      client:
        config:
          clients:
            url: http://localhost:8081
          staff:
            url: http://localhost:8084
          services:
            url: http://localhost:8082

feign:
  client:
    config:
      clients:
        basic-auth:
          username: user
          password: pass

#server:
#  error:
#    whitelabel:
#      enabled : false
logging:
  level:
    ru.jngvarr: DEBUG