server:
  port: 8081

spring:
  application:
    name: storage

  config:
    activate:
      on-profile: dev
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none


