server:
  port: 8082

spring:
  application:
    name: payment

  config:
    activate:
      on-profile: dev
    import:
     configserver: http://localhost:8888
  cloud:
    config:
      fail-fast: true

#  main:
#    web-application-type: reactive

#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false