server:
  port: 8082

spring:
  application:
    name: payment

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none


#  cloud:
#    config:
#      fail-fast: true

#  main:
#    web-application-type: reactive

#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false

#management:
#  endpoints:
#    web:
#      exposure:
#        include: metrics,prometheus