# Используем официальный образ Node.js для сборки
FROM node:18 as build

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY angularclient/package*.json  *.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем исходный код и собираем проект
COPY angularclient/dist .
RUN npm run build --prod

# Используем Nginx для сервировки файлов
FROM nginx:alpine

# Копируем собранные файлы Angular в Nginx
COPY --from=build /app/dist/your-angular-app /usr/share/nginx/html

# Открываем порт
EXPOSE 80
