#version: '3.8'
services:
  angular-client:
      build:
        context: .
      container_name: angular-client
      ports:
        - "80:80"
      networks:
        - app-network
networks:
  app-network:
