server:
  port: 8080

spring:
  application:
    name: web

  config:
    import: configserver:http://localhost:8888

#api:
#  storage:
#    baseUrl: http://localhost:8081/
#  payment:
#    baseUrl: http://localhost:8082/
