server:
  port: 8080

spring:
  application:
    name: web

#  config:
#    import: configserver:http://localhost:8888

api:
  storage:
    baseUri: http://localhost:8081/
  payment:
    baseUri: http://localhost:8082/
