spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jngvarr/SalonConfig.git
          default-label: main
          #          basedir: c:\..\gb\springConfig\
#            basedir: .\gb\springConfig\
server:
  port: 8888